# Generated by Django 5.2.4 on 2025-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='description',
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text="Check this to display a 'Best Seller' tag."),
        ),
        migrations.AddField(
            model_name='labtest',
            name='long_description',
            field=models.TextField(blank=True, help_text="A detailed 'About the test' description for the detail page."),
        ),
        migrations.AddField(
            model_name='labtest',
            name='preparation',
            field=models.TextField(blank=True, help_text='e.g., No special preparation is required. or Fasting for 8 hours is required.'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, help_text='e.g., Blood, Urine, Saliva', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief, one-sentence description for the test list page.'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(blank=True, help_text='e.g., In Person, At-Home Kit', max_length=100),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(help_text='e.g., Complete Blood Count (CBC) Test', max_length=200),
        ),
    ]
