# Generated by Django 5.2.4 on 2025-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_labtest_description_labtest_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_anonymous',
            field=models.BooleanField(default=True, help_text='Can this test be booked without an account?'),
        ),
        migrations.AddField(
            model_name='testpackage',
            name='is_best_seller',
            field=models.BooleanField(default=False, help_text="Check this to display a 'Best Seller' tag for the package."),
        ),
    ]
