# Generated by Django 5.2.4 on 2025-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_doctoraccesscode_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
